services:
  postgres:
    build:
      context: ./database
      dockerfile: dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PHP_DB_HOST=postgres
      - PHP_DB_PORT=${POSTGRES_PORT}
    volumes:
      - ./web:/var/www/html
    networks:
      - app-network

  # nginx:
  #   image: nginx:1.25.3-alpine
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - .:/var/www/html

networks:
  app-network:
    driver: bridge
